"""Add times_accessed column

Revision ID: 94a1fa9eb665
Revises: 5f9e687c1298
Create Date: 2022-01-08 17:49:43.876674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a1fa9eb665'
down_revision = '5f9e687c1298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('times_accessed', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'times_accessed')
    # ### end Alembic commands ###
