"""Add unique requirement to the content column of quote

Revision ID: fe2986a17ddf
Revises: 94a1fa9eb665
Create Date: 2022-01-10 16:58:17.515525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2986a17ddf'
down_revision = '94a1fa9eb665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'quotes', ['content'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='unique')
    # ### end Alembic commands ###
